import os
import math as m

PATH_TO_TABLES = "/utils/"
FILE_NAME = "pow2f_lut.h"
TABLE_LEN = 1024

file_header = """// autogenerated by scripts/generate_pow2f.py
// do not modify!!
#include<stdint.h>
#ifndef TABLES_POW2F_LUT_H_
#define TABLES_POW2F_LUT_H_
"""

array_footer = "};\n"
file_footer = "#endif  // TABLES_POW2F_LUT_H_"

def main():
    file_path = f"{os.getcwd()}{PATH_TO_TABLES}{FILE_NAME}"
    with open(file_path, 'w') as f:
        f.write(file_header)
        f.write(f"const float pow2f_lut[{TABLE_LEN}] = {{\n")
        for i in range(TABLE_LEN):
            ratio = 2**(i / TABLE_LEN)
            arr_write_item(f, i, ratio, 32, TABLE_LEN)
        f.write(array_footer)
        f.write(file_footer)
        
def arr_write_item(f, idx, val_to_write, vals_per_line, arr_len):
    if isinstance(val_to_write, float):
        val_to_write = f"{val_to_write:E}"
    if idx != arr_len-1:
        f.write(f"{val_to_write}, ")
    else:
        f.write(f"{val_to_write}")
    
    if (idx + 1) % vals_per_line == 0:
        f.write("\n")
    
if __name__ == "__main__":
    main()