import os
import math as m

PATH_TO_TABLES = "/utils/"
FILE_NAME = "sin2pif_lut.h"
TABLE_LEN = 1024

file_header = """// autogenerated by utils/generate_rp_sinf_LUT.py
// do not modify!!
#include<stdint.h>
#ifndef RPLIB_UTILS_RP_SIN2PIF_LUT_H_
#define RPLIB_UTILS_RP_SIN2PIF_LUT_H_
"""

array_footer = "};\n"
file_footer = "#endif  // RPLIB_UTILS_SIN2PIF_LUT_H_"

def main():
    file_path = f"{os.getcwd()}{PATH_TO_TABLES}{FILE_NAME}"
    with open(file_path, 'w') as f:
        f.write(file_header)
        f.write(f"const float sin2pif_lut[{TABLE_LEN}] = {{\n")
        for i in range(TABLE_LEN):
            x = m.sin(m.pi* (i / TABLE_LEN) * 2.0)
            arr_write_item(f, i, x, 32, TABLE_LEN)
        f.write(array_footer)
        f.write(file_footer)
        
def arr_write_item(f, idx, val_to_write, vals_per_line, arr_len):
    if isinstance(val_to_write, float):
        val_to_write = f"{val_to_write:E}"
    if idx != arr_len-1:
        f.write(f"{val_to_write}, ")
    else:
        f.write(f"{val_to_write}")
    
    if (idx + 1) % vals_per_line == 0:
        f.write("\n")
    
if __name__ == "__main__":
    main()